site_name: Trent Docs

theme:    readthedocs

pages:
    - 'Home': index.md
    - 'Nspawn': nspawn.md
    - 'Quick Dirty Redis Nspawn Container on Arch Linux': arch_redis_nspawn.md
    - 'Quick Dirty Postgresql Nspawn Container on Arch Linux': arch_postgresql_nspawn.md
    - 'Serve And Share Apps From Your Phone With Fdroid': server_and_share_apps_from_your_phone_with_fdroid.md

