site_name: Trent Docs

theme:    readthedocs

pages:
    - 'Home': index.md
    - 'LXD Container Home Server Networking For Dummies': lxd_container_home_server_networking_for_dummies.md
    - 'Serve And Share Apps From Your Phone With Fdroid': serve_and_share_apps_from_your_phone_with_fdroid.md
    - 'Nspawn': nspawn.md
    - 'Mastodon on Arch': mastodon_on_arch.md
    - 'Debian Nspawn Container On Arch For Testing Apache Configurations': debian_nspawn_container_on_arch_for_testing_apache_configurations.md
    - 'Dynamic Cacheing Nginx Reverse Proxy For Pacman': dynamic_cacheing_nginx_reverse_proxy_for_pacman.md
    - 'FreeBSD Jails on FreeNAS': freebsd_jails_on_freenas.md
    - 'Quick Dirty Redis Nspawn Container on Arch Linux': arch_redis_nspawn.md
    - 'Quick Dirty Postgresql Nspawn Container on Arch Linux': arch_postgresql_nspawn.md
    - 'Self Signed Certs': self_signed_certs.md
